### ISSUE TITLE
When running the game, there are bugs and the sound has static noise

### ISSUE THREAD

**Issue by LHYhorion** [esp-cpp/esp-box-emu#30]
### Answers checklist.

- [X] I have read the documentation and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

An error occurred while running the game：
E (78032) spi_master: check_trans_valid(796): trans tx_buffer should be NULL and SPI_TRANS_USE_TXDATA should be cleared to skip MOSI phase.
Couldn't queue trans: 258 'ESP_ERR_INVALID_ARG'
Additionally, it has been noticed that there is static noise while playing the background sound of the game.

**Comment by LHYhorion** [comment]
> @LHYhorion I've seen the transaction data bug before, though TBH I thought I'd fixed it.
> 
> Regarding sound - I have found that the NES sound emulation is not very good right now, though I think the GB/C sound should be better. Is the sound issue you're experiencing with the NES or the GB/C emulators?
> 
> Right now there are some bugs and crashes that can be triggered. As I get time I'm looking into what might be the cause of them as well as ways to fix them, though any help would be appreciated.

The sound of the NES emulator isn't very good, but I found that removing the 32-bit conversion and retaining the 16-bit sound makes it sound better. Regarding the error issue, I found that sometimes the 'length' is calculated as 0. Assigning a non-zero value when it's calculated as 0 will prevent the error.

**Comment by finger563** [comment]
Thanks for the tip about the sound conversion potentially being the root cause. I'll make the change and test if that improves the quality of the output sound on my side as well.

Regarding the length issue on the SPI transaction - in the transmit function i'm doing a length check on the data being sent so a length of 0 shouldn't be an issue.  Regarding your comment of `assigning a non-zero value when its calculated as 0` - what part of the code are you talking about here? Within the box-emu's `hal` component, the `nes` component, or within the `espp/display_drivers` component which is the main place the length is calculated for the SPI transaction data.
